add some common header/lib checks before building things as people often times dont actually install development packages before attempting to build stuff
git-svn-id: svn://localhost/svn/toolchain/trunk@1896 2adf4935-75e9-4407-93b2-34b21a1880a4

diff --git a/buildscript/BuildToolChain b/buildscript/BuildToolChain
--- a/buildscript/BuildToolChain
+++ b/buildscript/BuildToolChain
@@ -43,8 +43,10 @@ PREREQ_HW_SIM_TESTS=" bc kill killall pstree runtest Xvfb"
 BINUTILS_VERSION=2.17
 GCC_VERSIONS=
 NUM_JOBS=0
+SKIP_DEV_CHECKS=false
+WITHOUT_X=false
 
-while getopts b:B:c:C:dfH:hj:k:K:l:m:o:O:pr:s:StT:u:vwX parameter
+while getopts b:B:c:C:dDfH:hj:k:K:l:m:o:O:pr:s:StT:u:vwX parameter
 do
     case $parameter in
         p)
@@ -60,6 +62,9 @@ do
         d)
             DATE_STAMP=1
             echo "Outputfiles being date stamped"
+            ;;
+        D)
+            SKIP_DEV_CHECKS=true
             ;;
         v)
             VERBOSE=1
@@ -188,6 +193,7 @@ do
 -C FILE          Use FILE as uClibc config file, rather than the default.
 -c GCC_VERSION   GCC version (default 4.1).  Can be given multiple times.
 -d               Date Stamp all output files
+-D               Don't check libraries/headers -- assume all is OK
 -f               Add stack checking to all tests
 -h               Help
 -H HOST          Build toolchain to run on HOST.
@@ -219,6 +225,63 @@ echo "-T TARGET_IPADDR Test components on hardware
 done
 
 ############ Check and error if I can't find the things I need #
+
+check_header() {
+	local header=$1
+	printf "#include <$header>\n" | gcc -E - -o /dev/null
+}
+
+check_lib() {
+	local lib=$1
+	echo "int main(){}" | gcc -x c - -l${lib} -o /dev/null 1>/dev/null
+}
+
+# check_group(package name, header list, library list)
+check_source_group() {
+	local pkg=$1
+	local h headers=$2
+	local l libs=$3
+	local fail=0
+
+	for h in ${headers} ; do
+		check_header ${h} || fail=1
+	done
+	for l in ${libs} ; do
+		check_lib ${l} || fail=1
+	done
+
+	if [ -n "${pkg}" ] && [ ${fail} -eq 1 ] ; then
+		cat <<-EOF 1>&2
+		
+		You need to install some packages before building the toolchain.
+		
+		Your system lacks the development packages for:
+		    ${pkg}
+		
+		The headers you need:
+		    ${headers}
+		
+		The libs you need:
+		    ${libs}
+		
+		EOF
+		exit 1
+	fi
+
+	return ${fail}
+}
+
+check_source_packages() {
+	echo "Checking for development packages (skip checks with the -D option)"
+	check_source_group "zlib" "zlib.h" "z"
+	check_source_group "curses" "ncurses.h" "ncurses"
+	if ! check_source_group "" "X11/Xlib.h" "X11" ; then
+		echo "X development packages were not found, disabling gui packages such as insight" 1>&2
+		WITHOUT_X=true
+	fi
+}
+
+${SKIP_DEV_CHECKS} || check_source_packages
 
 if [ -n "$CHECK_PRE" ] ; then
     echo "Check http://gcc.gnu.org/install/prerequisites.html for more information"
