Don't build libdsp. Build libs instead.
git-svn-id: svn://localhost/svn/toolchain/trunk@1743 2adf4935-75e9-4407-93b2-34b21a1880a4

diff --git a/buildscript/BuildToolChain b/buildscript/BuildToolChain
--- a/buildscript/BuildToolChain
+++ b/buildscript/BuildToolChain
@@ -1315,54 +1315,6 @@ for GCC_VERSION in $GCC_VERSIONS; do
     rm -rf $DIR_GCC_BUILD/*
 done
 
-if [ -e $DIR_SOURCE/libdsp/Makefile ] ; then
-    echo -n "*** Building libdsp                " ; date
-
-    cd $DIR_SOURCE/libdsp
-    RUN="$MAKE clean"
-    (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-    (echo $RUN $LOGFILE ; ) | sh
-
-    RUN="CROSS=bfin-elf- $MAKE"
-    (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-    (echo $RUN $LOGFILE ; ) | sh || die_with_log
-
-    if [ ! -e $DIR_SOURCE/libdsp/libbffastfp.a ] ; then
-        echo "The ELF toolchain did not build libbffastfp.a properly - report an error"
-        tail -10 $ACTUAL_LOGFILE
-        exit 1
-    fi
-
-    echo -n "*** Installing libdsp              " ; date
-    RUN="cp $DIR_SOURCE/libdsp/libbffastfp.a $DIR_ELF_OUTPUT/bfin-elf/lib/libbffastfp.a"
-    (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-    (echo $RUN $LOGFILE ; ) | sh || die_with_log
-
-    RUN="$MAKE clean"
-    (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-    (echo $RUN $LOGFILE ; ) | sh
-
-    RUN="CROSS=bfin-elf- $MAKE CFLAGS=-mfdpic"
-    (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-    (echo $RUN $LOGFILE ; ) | sh || die_with_log
-
-    if [ ! -e $DIR_SOURCE/libdsp/libbffastfp.a ] ; then
-        echo "The ELF toolchain did not build libbffastfp.a properly - report an error"
-        tail -10 $ACTUAL_LOGFILE
-        exit 1
-    fi
-
-    echo -n "*** Installing libdsp              " ; date
-    RUN="cp $DIR_SOURCE/libdsp/libbffastfp.a $DIR_ELF_OUTPUT/bfin-elf/lib/mfdpic/libbffastfp.a"
-    (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-    (echo $RUN $LOGFILE ; ) | sh || die_with_log
-
-    cd $DIR_SOURCE/libdsp
-    RUN="$MAKE clean"
-    (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-    (echo $RUN $LOGFILE ; ) | sh
-fi
-
 # We cannot remove newlib symlink until the bfin-elf tests finishs.
 for GCC_VERSION in $GCC_VERSIONS; do
   DIR_GCC_SOURCE=$DIR_SOURCE/gcc-$GCC_VERSION
@@ -1683,20 +1635,6 @@ if [ $KERNEL_SOURCE ] ; then
         run_tests $DIR_TEST_HW2_RESULTS hardware
     fi
 
-    ##################### Install libbffastfp.a #####################
-
-    if [ -e $DIR_SOURCE/libdsp/Makefile ] ; then
-        echo -n "*** Installing uClinux libdsp      " ; date
-
-        RUN="cp $DIR_ELF_OUTPUT/bfin-elf/lib/libbffastfp.a $DIR_uC_OUTPUT/bfin-uclinux/lib/"
-        (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-        (echo $RUN $LOGFILE ; ) | sh || die_with_log
-
-        RUN="cp $DIR_ELF_OUTPUT/bfin-elf/lib/mfdpic/libbffastfp.a $DIR_LINUX_OUTPUT/bfin-linux-uclibc/lib/"
-        (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-        (echo $RUN $LOGFILE ; ) | sh || die_with_log
-    fi
-
     ########################### genext2fs ########################
 
     echo -n "*** Building uClinux genext2fs     " ; date
@@ -1863,7 +1801,88 @@ for GCC_VERSION in $GCC_VERSIONS; do
 done
 rm -rf $DIR_ELF2FLT_BUILD
 
+########################### Target libs ########################
+
+if [ -e $DIR_SOURCE/libs/Makefile ] ; then
+
+    cd $DIR_SOURCE/libs
+
+    MULTILIBS=`bfin-elf-gcc --print-multi-lib`
+
+    echo -n "*** Building libs                  " ; date
+
+    for ml in $MULTILIBS; do
+
+	dir=`echo ${ml} | sed -e 's/;.*$//'`
+	flags=`echo ${ml} | sed -e 's/^[^;]*;//' -e 's/@/ -/g'`
+
+	RUN="$MAKE clean"
+	(echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
+	(echo $RUN $LOGFILE ; ) | sh
+
+	RUN="$MAKE MULTILIB_FLAGS=\"$flags\""
+	(echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
+	(echo $RUN $LOGFILE ; ) | sh
+
+	if [ ! -e $DIR_SOURCE/libs/libdsp/libbfdsp.a ] ; then
+	    echo "libbfdsp.a $flags build error - report an error"
+	    tail -10 $ACTUAL_LOGFILE
+	    exit 1
+	fi
+
+	if [ ! -e $DIR_SOURCE/libs/libdsp/libbffastfp.a ] ; then
+	    echo "libbffastfp.a $flags build error - report an error"
+	    tail -10 $ACTUAL_LOGFILE
+	    exit 1
+	fi
+
+	if [ $KERNEL_SOURCE ] ; then
+	    if echo "${flags}" | grep -q mfdpic; then
+		RUN="$MAKE install DESTDIR=$DIR_LINUX_OUTPUT/bfin-linux-uclibc/runtime USR=/usr SUFFIX=/$dir MULTILIB="
+		(echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
+		(echo $RUN $LOGFILE ; ) | sh
+	    else
+		RUN="$MAKE install DESTDIR=$DIR_uC_OUTPUT/bfin-uclinux/runtime USR=/usr SUFFIX= MULTILIB=/$dir"
+		(echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
+		(echo $RUN $LOGFILE ; ) | sh
+	    fi
+	fi
+
+	RUN="$MAKE LIBC_HAS_NO_CMATH=1 MULTILIB_FLAGS=\"$flags\""
+	(echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
+	(echo $RUN $LOGFILE ; ) | sh
+
+	RUN="$MAKE LIBC_HAS_NO_CMATH=1 install DESTDIR=$DIR_ELF_OUTPUT/bfin-elf USR= SUFFIX= MULTILIB=/$dir"
+	(echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
+	(echo $RUN $LOGFILE ; ) | sh
+    done
+
+    RUN="$MAKE clean"
+    (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
+    (echo $RUN $LOGFILE ; ) | sh
+fi
+
+# $1 is the file to fix
+# $2 is the line before which the line is inserted.
+# $3 is the line to insert.
+insert_line ()
+{
+    sed "/$2/i\
+    $3" $1 > $1.tmp.$$
+    mv $1.tmp.$$ $1
+}
+
+insert_line $DIR_ELF_OUTPUT/bfin-elf/include/math.h "^#endif \/\* _MATH_H_ \*\/" "#include <math_bf.h>"
+if [ $KERNEL_SOURCE ] ; then
+    insert_line $DIR_uC_OUTPUT/bfin-uclinux/runtime/usr/include/math.h "^#endif \/\* math\.h  \*\/" "#include <math_bf.h>"
+    insert_line $DIR_LINUX_OUTPUT/bfin-linux-uclibc/runtime/usr/include/math.h "^#endif \/\* math\.h  \*\/" "#include <math_bf.h>"
+    insert_line $DIR_uC_OUTPUT/bfin-uclinux/runtime/usr/include/complex.h "^#endif \/\* complex\.h \*\/" "#include <complex_bf.h>"
+    insert_line $DIR_LINUX_OUTPUT/bfin-linux-uclibc/runtime/usr/include/complex.h "^#endif \/\* complex\.h \*\/" "#include <complex_bf.h>"
+fi
+
 ########################### Target binutils ########################
+
+if [ $KERNEL_SOURCE ] ; then
 
 export PATH=$DIR_uC_OUTPUT/bin:$DIR_LINUX_OUTPUT/bin:$PATH
 
@@ -1914,5 +1933,7 @@ RUN="$MAKE install-bfd install-opcodes install-libiberty"
 (echo $RUN $LOGFILE ; ) | sh
 
 rm -rf $DIR_BINUTILS_BUILD
+
+fi
 
 echo -n "*** Done                           " ; date
