if fast make fails, fall back to portable configure/make
git-svn-id: svn://localhost/svn/toolchain/trunk@1877 2adf4935-75e9-4407-93b2-34b21a1880a4

diff --git a/buildscript/BuildToolChain b/buildscript/BuildToolChain
--- a/buildscript/BuildToolChain
+++ b/buildscript/BuildToolChain
@@ -1717,22 +1717,41 @@ if [ $KERNEL_SOURCE ] ; then
 
 	######################## ldr-utils ###########################
 
-    echo -n "*** Building uClinux ldr-utils      " ; date
+    echo -n "*** Building ldr-utils              " ; date
     cd $DIR_LDR_UTILS_SOURCE
 
-    echo -n "*** Cleaning uClinux ldr-utils      " ; date
+    echo -n "*** Cleaning ldr-utils              " ; date
     RUN="$MAKE clean "
     (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
     (echo $RUN $LOGFILE ; ) | sh
 
-    echo -n "*** Make uClinux ldr-utils          " ; date
+    echo -n "*** Make ldr-utils                  " ; date
     RUN=$MAKE
     (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh
-    (echo $RUN $LOGFILE ; ) | sh
+    if ! (echo $RUN $LOGFILE ; ) | sh ; then
+        # If simple build failed, try autotool version
+        find . | xargs touch -r . # fix autotool timestamps
+        DIR_LDR_UTILS_BUILD=$DIR_BUILD/ldr-utils_build
+        rm -rf "$DIR_LDR_UTILS_BUILD"
+        mkdir -p "$DIR_LDR_UTILS_BUILD"
+        cd "$DIR_LDR_UTILS_BUILD"
+        RUN="$DIR_LDR_UTILS_SOURCE/configure --prefix=/usr $BUILD_TARGET $HOST_TARGET"
+        (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh || die_with_log
+        RUN=$MAKE
+        (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh || die_with_log
+    else
+        DIR_LDR_UTILS_BUILD=$DIR_LDR_UTILS_SOURCE
+    fi
+
+    if [ "$CHECK_ON_SIMULATOR" = "1" ] ; then
+        echo -n "*** Checking ldr-utils              " ; date
+        RUN="$MAKE check"
+        (echo "echo -e '###\n$RUN\n' $LOGFILE" ) | sh || die_with_log
+    fi
 
     for RUN in ldr
     do
-        if [ ! -f $DIR_LDR_UTILS_SOURCE/$RUN ] ; then
+        if [ ! -f $DIR_LDR_UTILS_BUILD/$RUN ] ; then
             echo "ldr-utils did not build properly : Missing $RUN"
             echo "Please report an error to http://blackfin.uclinux.org"
             tail -10 $ACTUAL_LOGFILE
@@ -1740,10 +1759,14 @@ if [ $KERNEL_SOURCE ] ; then
         fi
     done
 
-    echo -n "*** Installing uClinux ldr-utils    " ; date
-    cp $DIR_LDR_UTILS_SOURCE/ldr $DIR_ELF_OUTPUT/bin/bfin-elf-ldr || exit 1
-    cp $DIR_LDR_UTILS_SOURCE/ldr $DIR_uC_OUTPUT/bin/bfin-uclinux-ldr || exit 1
-    mv $DIR_LDR_UTILS_SOURCE/ldr $DIR_LINUX_OUTPUT/bin/bfin-linux-uclibc-ldr || exit 1
+    echo -n "*** Installing ldr-utils            " ; date
+    cp $DIR_LDR_UTILS_BUILD/ldr $DIR_ELF_OUTPUT/bin/bfin-elf-ldr || exit 1
+    cp $DIR_LDR_UTILS_BUILD/ldr $DIR_uC_OUTPUT/bin/bfin-uclinux-ldr || exit 1
+    mv $DIR_LDR_UTILS_BUILD/ldr $DIR_LINUX_OUTPUT/bin/bfin-linux-uclibc-ldr || exit 1
+
+    if [ "$DIR_LDR_UTILS_BUILD" != "$DIR_LDR_UTILS_SOURCE" ] ; then
+        rm -rf "$DIR_LDR_UTILS_BUILD"
+    fi
 
     ######################## U-Boot ##############################
 
