import upstream urjtag svn rev 1152
git-svn-id: svn://localhost/svn/toolchain/trunk@2227 2adf4935-75e9-4407-93b2-34b21a1880a4

diff --git a/jtag/configure b/jtag/configure
--- a/jtag/configure
+++ b/jtag/configure
@@ -747,6 +747,8 @@ ENABLE_JIM_TRUE
 ENABLE_JIM_FALSE
 JEDEC_EXP_TRUE
 JEDEC_EXP_FALSE
+JTAG_RELOCATABLE_TRUE
+JTAG_RELOCATABLE_FALSE
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1351,6 +1353,7 @@ Optional Features:
   --enable-bsdl           Enable BSDL subsystem (default is enabled)
   --enable-jim            Enable JTAG target simulator JIM
   --enable-jedec-exp      Enable experimental JEDEC flash detection
+  --enable-relocatable    Enable relocatable paths
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -9657,6 +9660,43 @@ fi
 fi
 
 
+# Check whether --enable-relocatable was given.
+if test "${enable_relocatable+set}" = set; then
+  enableval=$enable_relocatable; relocatable=$enableval
+else
+  relocatable=no
+fi
+
+if test "x$relocatable" = xyes; then
+
+   if true; then
+  JTAG_RELOCATABLE_TRUE=
+  JTAG_RELOCATABLE_FALSE='#'
+else
+  JTAG_RELOCATABLE_TRUE='#'
+  JTAG_RELOCATABLE_FALSE=
+fi
+
+
+cat >>confdefs.h <<\_ACEOF
+#define JTAG_RELOCATABLE 1
+_ACEOF
+
+
+else
+
+   if false; then
+  JTAG_RELOCATABLE_TRUE=
+  JTAG_RELOCATABLE_FALSE='#'
+else
+  JTAG_RELOCATABLE_TRUE='#'
+  JTAG_RELOCATABLE_FALSE=
+fi
+
+
+fi
+
+
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -9918,6 +9958,20 @@ if test -z "${JEDEC_EXP_TRUE}" && test -z "${JEDEC_EXP_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"JEDEC_EXP\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"JEDEC_EXP\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${JTAG_RELOCATABLE_TRUE}" && test -z "${JTAG_RELOCATABLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"JTAG_RELOCATABLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"JTAG_RELOCATABLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${JTAG_RELOCATABLE_TRUE}" && test -z "${JTAG_RELOCATABLE_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"JTAG_RELOCATABLE\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"JTAG_RELOCATABLE\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -10646,11 +10700,13 @@ ENABLE_JIM_TRUE!$ENABLE_JIM_TRUE$ac_delim
 ENABLE_JIM_FALSE!$ENABLE_JIM_FALSE$ac_delim
 JEDEC_EXP_TRUE!$JEDEC_EXP_TRUE$ac_delim
 JEDEC_EXP_FALSE!$JEDEC_EXP_FALSE$ac_delim
+JTAG_RELOCATABLE_TRUE!$JTAG_RELOCATABLE_TRUE$ac_delim
+JTAG_RELOCATABLE_FALSE!$JTAG_RELOCATABLE_FALSE$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 35; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 37; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
