Merged bfin changes to 2.15
git-svn-id: svn://localhost/svn/toolchain/trunk@121 2adf4935-75e9-4407-93b2-34b21a1880a4

diff --git a/binutils/binutils-2.15/opcodes/configure b/binutils/binutils-2.15/opcodes/configure
--- a/binutils/binutils-2.15/opcodes/configure
+++ b/binutils/binutils-2.15/opcodes/configure
@@ -2352,7 +2352,7 @@ fi
 
 
 if test -z "$target" ; then
-    { echo "configure: error: Unrecognized target system type; please check config.sub." 1>&2; exit 1; }
+    { echo "configure: error: Unrecognized target system type ; please check config.sub." 1>&2; exit 1; }
 fi
 
 echo $ac_n "checking whether to enable maintainer-specific portions of Makefiles""... $ac_c" 1>&6
@@ -4660,6 +4660,7 @@ if test x${all_targets} = xfalse ; then
 	bfd_mmix_arch)		ta="$ta mmix-dis.lo mmix-opc.lo" ;;
 	bfd_mn10200_arch)	ta="$ta m10200-dis.lo m10200-opc.lo" ;;
 	bfd_mn10300_arch)	ta="$ta m10300-dis.lo m10300-opc.lo" ;;
+	bfd_bfin_arch)		ta="$ta bfin-dis.lo" ;;
 	bfd_msp430_arch)	ta="$ta msp430-dis.lo" ;;
 	bfd_ns32k_arch)		ta="$ta ns32k-dis.lo" ;;
 	bfd_openrisc_arch)	ta="$ta openrisc-asm.lo openrisc-desc.lo openrisc-dis.lo openrisc-ibld.lo openrisc-opc.lo" using_cgen=yes ;;
