Import r2264 make sure we are running on a case sensitive filesystem
git-svn-id: svn://localhost/svn/toolchain/trunk@3042 2adf4935-75e9-4407-93b2-34b21a1880a4

diff --git a/buildscript-experimental/toolchain-build b/buildscript-experimental/toolchain-build
--- a/buildscript-experimental/toolchain-build
+++ b/buildscript-experimental/toolchain-build
@@ -714,6 +714,17 @@ if [ ! -d /.$DIR_BUILD ] ; then
 fi
 echo "Build will be done in       $DIR_BUILD"
 
+# make sure we arent running on a case insensitive filesystem
+cd $DIR_BUILD
+rm -rf .case.test .CASE.test
+echo case > .case.test
+case=$(cat .CASE.test 2>/dev/null)
+if [ "$case" = "case" ] ; then
+	echo "ERROR: you must use a case sensitive filesystem"
+	exit 1
+fi
+rm -rf .case.test .CASE.test
+
 DIR_BINUTILS_BUILD=$DIR_BUILD/binutils_build
 DIR_ELF2FLT_BUILD=$DIR_BUILD/elf2flt_build
 DIR_GENEXT2FS_BUILD=$DIR_BUILD/genext2fs_build
diff --git a/buildscript-experimental/toolchain-regtest b/buildscript-experimental/toolchain-regtest
--- a/buildscript-experimental/toolchain-regtest
+++ b/buildscript-experimental/toolchain-regtest
@@ -501,6 +501,17 @@ if [ ! -d /.$DIR_BUILD ] ; then
 fi
 echo "Build will be done in       $DIR_BUILD"
 
+# make sure we arent running on a case insensitive filesystem
+cd $DIR_BUILD
+rm -rf .case.test .CASE.test
+echo case > .case.test
+case=$(cat .CASE.test 2>/dev/null)
+if [ "$case" = "case" ] ; then
+	echo "ERROR: you must use a case sensitive filesystem"
+	exit 1
+fi
+rm -rf .case.test .CASE.test
+
 DIR_LOG=$DIR_BUILD/logs
 if [ ! -d $DIR_LOG ] ; then
     mkdir $DIR_LOG
