merge testing fixes from BuildToolChain
git-svn-id: svn://localhost/svn/toolchain/trunk@3906 2adf4935-75e9-4407-93b2-34b21a1880a4

diff --git a/buildscript-experimental/toolchain-regtest b/buildscript-experimental/toolchain-regtest
--- a/buildscript-experimental/toolchain-regtest
+++ b/buildscript-experimental/toolchain-regtest
@@ -853,7 +853,7 @@ if [ $TEST_TARGET_UCLINUX ] || [ $TEST_TARGET_LINUX_UCLIBC ] ; then
        rsh -l root $TARGET_IPADDR echo 1 \> /proc/sys/net/ipv4/tcp_tw_recycle
        RUN=`rsh -l root $TARGET_IPADDR cat /proc/sys/net/ipv4/tcp_tw_recycle 2>/dev/null`
        if [ "x$RUN" = "x0" ] ; then
-	   echo "Failure"
+           echo "Failure"
            echo "Could not set target $TARGET_IPADDR /proc/sys/net/ipv4/tcp_tw_recycle to 1"
            exit 1
        else
@@ -877,11 +877,12 @@ if [ $TEST_TARGET_UCLINUX ] || [ $TEST_TARGET_LINUX_UCLIBC ] ; then
         echo "    Hardware tests will be compiled with optional stack overflow checking"
     fi
     if [ $TEST_TARGET_LINUX_UCLIBC ] ; then
-	if [ $FDPIC_TARGET -eq 0 ] ; then
-            echo "    Looks like flat userspace - will copy over /lib/*.so when testing"
-	else
-            echo "    Looks like fdpic userspace - will warn if /lib/*.so are different (not implemented yet)"
-	fi
+        if [ $FDPIC_TARGET -eq 0 ] ; then
+            echo "    Looks like flat userspace - I'll check /lib/*.so are the same when testing"
+        else
+            echo "    Your Target looks like it is running FDPIC userspace - I can't test on fdpic targets. Stopping"
+            exit 1
+        fi
     fi
 
     RUN=`rsh -l root $TARGET_IPADDR "ps | grep syslog | grep -v grep | grep -v \"l 6\" | wc -l"`
@@ -2032,22 +2033,22 @@ prepare_target_solibs()
 
     if [ $FDPIC_TARGET -eq 0 ] ; then
 
-	detect_gcc gcc
-	if [ $? -eq 1 ] ; then
-	    return
-	fi
+        detect_gcc gcc
+        if [ $? -eq 1 ] ; then
+            return
+        fi
 
-	echo_date "Checking shared libraries on target"
+        echo_date "Checking shared libraries on target"
 
         GCC_BUILD=$DIR_BUILD/gcc_build-$GCC_VERSION
         mkdir -p $GCC_BUILD/libs_for_target
         rm -f $GCC_BUILD/libs_for_target/*
-        rsh -l root ${TARGET_IPADDR} "rm -f /lib/*so*"
         t=`$target_alias-gcc -mcpu=${CPU_TYPE_REV} -print-file-name=libc.a`
         t=`dirname $t`/../..
         for FILE in $t/lib/*so*
         do
             if ([ -e $FILE ] && [ -h $FILE ]) ; then
+                # don't check sym links
                 LIB=`readlink $FILE`
                 FILE=`basename $FILE`
                 LIB=`basename $LIB`
@@ -2056,8 +2057,13 @@ prepare_target_solibs()
                 if [ -f $FILE ] ; then
                     LIB=`basename ${FILE}`
                     $target_alias-strip $FILE -o $GCC_BUILD/libs_for_target/${LIB}
-                    rcp $GCC_BUILD/libs_for_target/${LIB} root@${TARGET_IPADDR}:/lib/${LIB}
-                    rsh -l root ${TARGET_IPADDR} "chmod +x /lib/${LIB}"
+                    BOARD_LIB=`rsh -l root ${TARGET_IPADDR} "md5sum /lib/${LIB} | awk '{print \\$1}'"`
+                    TEST_LIB=`md5sum $GCC_BUILD/libs_for_target/${LIB} | awk {print $1}`
+                    if [ "$BOARD_LIB" != "$TEST_LIB" ] ; then
+                        echo "Libs on board are different, aborting tests"
+                        echo "specifically ${LIB} and ${FILE}"
+                        exit 1
+                    fi
                 fi
             fi
         done
@@ -2194,24 +2200,24 @@ run_tests ()
     testcase=
     for testcase in `find $DIR_BUILD -name \*.gdb -type f `
     do
-            if [ ! -e ${testcase%\.gdb} ] ; then
-                 rm $testcase
-            fi
+        if [ ! -e ${testcase%\.gdb} ] ; then
+            rm $testcase
+        fi
     done
 
     echo_date "Done testing  - results"
 
     FILES=
     if [ $BINUTILS_VERSION ] ; then
-	FILES=`find $1 -name "*${BINUTILS_VERSION}.sum" | sort`
+        FILES=`find $1 -name "*${BINUTILS_VERSION}.sum" | sort`
     fi
     if [ $GCC_VERSION ] ; then
-	FILES="$FILES `find $1 -name "*${GCC_VERSION}.sum" | sort`"
+        FILES="$FILES `find $1 -name "*${GCC_VERSION}.sum" | sort`"
     fi
     for FILE in $FILES
     do
-	echo
-	echo ${FILE##*/}
+        echo
+        echo ${FILE##*/}
         egrep "=== .*Sum.* ===|^# of" $FILE
         if [ -n "$RESULTS2COMPARE" ] ; then
             COMP=`basename $FILE`
